openapi: 3.0.3
info:
  title: Attendee API
  version: 1.0.0
  description: Meetings bots made easy
paths:
  /api/v1/bots:
    post:
      operationId: Create Bot
      description: After being created, the bot will attempt to join the specified
        meeting.
      summary: Create a new bot
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      tags:
      - Bots
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBotRequest'
            examples:
              ValidMeetingURL:
                value:
                  meeting_url: https://zoom.us/j/123?pwd=456
                  bot_name: My Bot
                summary: Valid meeting URL
                description: Example of a valid Zoom meeting URL
        required: true
      security:
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bot'
              examples:
                NewBot:
                  value:
                    id: bot_weIAju4OXNZkDTpZ
                    meeting_url: https://zoom.us/j/123?pwd=456
                    state: joining
                    events:
                    - type: join_requested
                      created_at: '2024-01-18T12:34:56Z'
                    transcription_state: not_started
                    recording_state: not_started
                  summary: New bot
                  description: Example response when creating a new bot
          description: Bot created successfully
        '400':
          description: Invalid input
  /api/v1/bots/{object_id}:
    get:
      operationId: Get Bot
      summary: Get the details for a bot
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        description: Bot ID
        required: true
        examples:
          BotIDExample:
            value: bot_xxxxxxxxxxx
            summary: Bot ID Example
      tags:
      - Bots
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bot'
              examples:
                NewBot:
                  value:
                    id: bot_weIAju4OXNZkDTpZ
                    meeting_url: https://zoom.us/j/123?pwd=456
                    state: joining
                    events:
                    - type: join_requested
                      created_at: '2024-01-18T12:34:56Z'
                    transcription_state: not_started
                    recording_state: not_started
                  summary: New bot
                  description: Example response when creating a new bot
          description: Bot details
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/leave:
    post:
      operationId: Leave Meeting
      description: Causes the bot to leave the meeting.
      summary: Leave a meeting
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        description: Bot ID
        required: true
        examples:
          BotIDExample:
            value: bot_xxxxxxxxxxx
            summary: Bot ID Example
      tags:
      - Bots
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bot'
              examples:
                LeavingBot:
                  value:
                    id: bot_weIAju4OXNZkDTpZ
                    meeting_url: https://zoom.us/j/123?pwd=456
                    state: leaving
                    events:
                    - type: join_requested
                      created_at: '2024-01-18T12:34:56Z'
                    - type: joined_meeting
                      created_at: '2024-01-18T12:35:00Z'
                    - type: leave_requested
                      created_at: '2024-01-18T13:34:56Z'
                    transcription_state: in_progress
                    recording_state: in_progress
                  summary: Leaving Bot
                  description: Example response when requesting a bot to leave
          description: Successfully requested to leave meeting
        '400':
          description: Bot is not in a valid state to leave the meeting
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/speech:
    post:
      operationId: Output speech
      description: Causes the bot to speak a message in the meeting.
      summary: Output speech
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        description: Bot ID
        required: true
        examples:
          BotIDExample:
            value: bot_xxxxxxxxxxx
            summary: Bot ID Example
      tags:
      - Bots
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpeechRequest'
            examples:
              ValidSpeechRequest:
                value:
                  text: Hello, this is a bot speaking text.
                  text_to_speech_settings:
                    google:
                      voice_language_code: en-US
                      voice_name: en-US-Casual-K
                summary: Valid speech request
                description: Example of a valid speech request
        required: true
      security:
      - {}
      responses:
        '200':
          description: Speech request created successfully
        '400':
          description: Invalid input
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/output_audio:
    post:
      operationId: Output Audio
      description: Causes the bot to output audio in the meeting.
      summary: Output audio
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        description: Bot ID
        required: true
        examples:
          BotIDExample:
            value: bot_xxxxxxxxxxx
            summary: Bot ID Example
      tags:
      - Bots
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                  - audio/mp3
                data:
                  type: string
                  format: binary
                  description: Base64 encoded audio data
              required:
              - type
              - data
      security:
      - {}
      responses:
        '200':
          description: Audio request created successfully
        '400':
          description: Invalid input
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/output_image:
    post:
      operationId: Output Image
      description: Causes the bot to output an image in the meeting.
      summary: Output image
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        description: Bot ID
        required: true
        examples:
          BotIDExample:
            value: bot_xxxxxxxxxxx
            summary: Bot ID Example
      tags:
      - Bots
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                  - image/png
                data:
                  type: string
                  format: binary
                  description: Base64 encoded image data
              required:
              - type
              - data
      security:
      - {}
      responses:
        '200':
          description: Image request created successfully
        '400':
          description: Invalid input
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/recording:
    get:
      operationId: Get Bot Recording
      description: Returns a short-lived S3 URL for the recording of the bot.
      summary: Get the recording for a bot
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        description: Bot ID
        required: true
        examples:
          BotIDExample:
            value: bot_xxxxxxxxxxx
            summary: Bot ID Example
      tags:
      - Bots
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recording'
              examples:
                RecordingUpload:
                  value:
                    url: https://attendee-short-term-storage-production.s3.amazonaws.com/e4da3b7fbbce2345d7772b0674a318d5.mp4?...
                    start_timestamp_ms: 1733114771000
                  summary: Recording Upload
          description: Short-lived S3 URL for the recording
  /api/v1/bots/{object_id}/transcript:
    get:
      operationId: Get Bot Transcript
      description: If the meeting is still in progress, this returns the transcript
        so far.
      summary: Get the transcript for a bot
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        description: Bot ID
        required: true
        examples:
          BotIDExample:
            value: bot_xxxxxxxxxxx
            summary: Bot ID Example
      tags:
      - Bots
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TranscriptUtterance'
          description: List of transcribed utterances
        '404':
          description: Bot not found
components:
  schemas:
    Bot:
      type: object
      properties:
        id:
          type: string
        meeting_url:
          type: string
          readOnly: true
        state:
          allOf:
          - $ref: '#/components/schemas/StateEnum'
          readOnly: true
        events:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              sub_type:
                type: string
                nullable: true
              created_at:
                type: string
                format: date-time
          readOnly: true
        transcription_state:
          allOf:
          - $ref: '#/components/schemas/TranscriptionStateEnum'
          readOnly: true
        recording_state:
          allOf:
          - $ref: '#/components/schemas/RecordingStateEnum'
          readOnly: true
      required:
      - events
      - id
      - meeting_url
      - recording_state
      - state
      - transcription_state
    CreateBotRequest:
      type: object
      properties:
        meeting_url:
          type: string
          minLength: 1
          description: The URL of the meeting to join, e.g. https://zoom.us/j/123?pwd=456
        bot_name:
          type: string
          minLength: 1
          description: The name of the bot to create, e.g. 'My Bot'
        transcription_settings:
          type: object
          properties:
            deepgram:
              type: object
              properties:
                language:
                  type: string
                  description: 'The language code for transcription (e.g. ''en'').
                    See here for available languages: https://developers.deepgram.com/docs/models-languages-overview'
                detect_language:
                  type: boolean
                  description: Whether to automatically detect the spoken language
          required:
          - deepgram
          default:
            deepgram:
              language: en
          description: 'The transcription settings for the bot, e.g. {''deepgram'':
            {''language'': ''en''}}'
        rtmp_settings:
          type: object
          properties:
            destination_url:
              type: string
              description: The URL of the RTMP server to send the stream to
            stream_key:
              type: string
              description: The stream key to use for the RTMP server
          required:
          - destination_url
          - stream_key
          description: 'RTMP server to stream to, e.g. {''destination_url'': ''rtmp://global-live.mux.com:5222/app'',
            ''stream_key'': ''xxxx''}.'
        recording_settings:
          type: object
          properties:
            format:
              type: string
              description: The format of the recording to save. The supported formats
                are 'webm' and 'mp4'.
          required:
          - format
          default:
            format: webm
          description: 'The settings for the bot''s recording. Either {''format'':
            ''webm''} or {''format'': ''mp4''}.'
      required:
      - bot_name
      - meeting_url
    Recording:
      type: object
      properties:
        url:
          type: string
          readOnly: true
        start_timestamp_ms:
          type: integer
      required:
      - start_timestamp_ms
      - url
    RecordingStateEnum:
      type: string
      enum:
      - not_started
      - in_progress
      - complete
      - failed
    SpeechRequest:
      type: object
      properties:
        text:
          type: string
          minLength: 1
        text_to_speech_settings:
          type: object
          properties:
            google:
              type: object
              properties:
                voice_language_code:
                  type: string
                  description: The voice language code (e.g. 'en-US'). See https://cloud.google.com/text-to-speech/docs/voices
                    for a list of available language codes and voices.
                voice_name:
                  type: string
                  description: The name of the voice to use (e.g. 'en-US-Casual-K')
          required:
          - google
      required:
      - text
      - text_to_speech_settings
    StateEnum:
      type: string
      enum:
      - ready
      - joining
      - joined_not_recording
      - joined_recording
      - leaving
      - ended
      - fatal_error
      - waiting_room
    TranscriptUtterance:
      type: object
      properties:
        speaker_name:
          type: string
        speaker_uuid:
          type: string
        speaker_user_uuid:
          type: string
          nullable: true
        timestamp_ms:
          type: integer
        duration_ms:
          type: integer
        transcription: {}
      required:
      - duration_ms
      - speaker_name
      - speaker_user_uuid
      - speaker_uuid
      - timestamp_ms
      - transcription
    TranscriptionStateEnum:
      type: string
      enum:
      - not_started
      - in_progress
      - complete
      - failed
servers:
- url: https://app.attendee.dev
  description: Production server
tags:
- name: Bots
  description: Bot management endpoints
